apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-provisioner
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-7"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-provisioner
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-provisioner
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-provisioner
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.provisioner.image.repository }}:{{ .Values.provisioner.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{.Values.provisioner.image.pullPolicy}}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-conf
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-conf
                  key: port
            - name: MASTER_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-conf
                  key: password
            - name: MASTER_DBUSER
              valueFrom:
                secretKeyRef:
                  name: database-conf
                  key: user
            - name: DB_USER
              value: {{ .Values.database.username }}
            - name: DB_NAME
              value: {{ .Values.database.name }}