apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-provisioner
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded